# Generated by Django 5.2.6 on 2026-01-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOption',
        ),
    ]
