# Generated by Django 5.2.6 on 2026-01-18 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_remove_shippingcharge_cart'),
        ('cart', '0004_vat_remove_cart_count_items_remove_cart_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.shippingcharge'),
        ),
    ]
