# Generated by Django 5.2.6 on 2026-01-24 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_remove_shippingcharge_cart'),
        ('cart', '0005_cart_shipping_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_charge',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.shippingcharge'),
        ),
    ]
