# Generated by Django 5.2.6 on 2026-01-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_orderitem_product_name_order_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AddField(
            model_name='order',
            name='products_name',
            field=models.CharField(blank=True, help_text='Comma-separated product names for this order.', max_length=1024, null=True),
        ),
    ]
