# Generated by Django 5.2.6 on 2026-01-18 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
        ('cart', '0004_vat_remove_cart_count_items_remove_cart_coupon_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingCharge',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='block_sector',
        ),
        migrations.RemoveField(
            model_name='address',
            name='delivery_note',
        ),
        migrations.RemoveField(
            model_name='address',
            name='flat_no',
        ),
        migrations.RemoveField(
            model_name='address',
            name='floor_no',
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='address.postalcode'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
