# Generated by Django 5.2.6 on 2026-01-18 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_delete_shippingcharge_remove_address_address_type_and_more'),
        ('cart', '0004_vat_remove_cart_count_items_remove_cart_coupon_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postalcode',
            name='shipping_charge',
        ),
        migrations.CreateModel(
            name='ShippingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_charges', to='cart.cart')),
            ],
        ),
    ]
