# Generated by Django 5.2.6 on 2026-01-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_remove_postalcode_shipping_charge_shippingcharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingcharge',
            name='cart',
        ),
    ]
