# Generated by Django 5.2.6 on 2026-01-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_remove_shippingcharge_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcharge',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
