# Generated by Django 5.2.6 on 2026-01-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_shippingcharge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcharge',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
