# Generated by Django 5.2.6 on 2026-01-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_shippingcharge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='block_sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='flat_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='floor_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
